# Generated by Django 5.0.7 on 2024-07-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AddField(
            model_name="item",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
