# Generated by Django 5.0.7 on 2024-07-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_category_options_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="banner",
            field=models.ImageField(
                blank=True, default="imagenotfound.jpg", upload_to=""
            ),
        ),
    ]
