# Generated by Django 5.0.7 on 2024-07-29 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_item_banner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="banner",
            new_name="image",
        ),
    ]
