# Generated by Django 5.0.7 on 2024-07-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_rename_banner_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, default="images/imagenotfound.jpg", upload_to=""
            ),
        ),
    ]
