# Generated by Django 5.0.7 on 2024-08-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_cart_items_cartitem_added_cartitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, default="assets/imagenotfound.jpg", upload_to=""
            ),
        ),
    ]
