# Generated by Django 5.0.7 on 2024-08-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_auto_20240806_2038"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(
                default="djangodbmodelsfieldscharfield",
                editable=False,
                max_length=100,
                unique=True,
            ),
        ),
    ]
